import { FormEvent, ReactNode, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const API = "http://localhost:8000/api/v1";
type SetupState = "loading" | "required" | "complete" | "error";
type ChatMessage = { id?: string; role: string; content: string; status?: string };
type ModelRecord = { id: string; model: string; name: string; provider: string; status: string; metadata: { size_bytes?: number } };
type AgentRecord = { id: string; key: string; name: string; status: string };
type TaskRecord = { id: string; type: string; status: string; progress: { message: string } };
type ConversationRecord = { id: string; title: string; model: string };
type WorkflowRecord = { id: string; name: string; description: string; status: string };
type WorkflowVersion = { id: string; number: number; status: string; graph: { nodes: object[]; edges: object[] } };
type WorkflowDetail = WorkflowRecord & { versions: WorkflowVersion[] };
type PluginRecord = { id: string; name: string; version: string; status: string };
type MemoryRecord = { id: string; namespace: string; scope: string; content: string; created_at: string };
type AuditRecord = { id: string; action: string; target_type: string; target_id: string; outcome: string; created_at: string };
type SystemStatus = { version: string; ollama: { status: string; model_count: number; detail: string } };
type UserRecord = { id: string; email: string; display_name: string; status: string; roles: string[] };
type Page = "home" | "chat" | "models" | "agents" | "workflows" | "plugins" | "tasks" | "memory" | "audit" | "system" | "users";

function inlineMarkdown(text: string): ReactNode[] {
  return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map((part, index) => {
    if (part.startsWith("**") && part.endsWith("**")) return <strong key={index}>{part.slice(2, -2)}</strong>;
    if (part.startsWith("`") && part.endsWith("`")) return <code key={index}>{part.slice(1, -1)}</code>;
    return part;
  });
}

function MarkdownMessage({ content }: { content: string }): JSX.Element {
  const parts = content.split(/```(?:[\w+-]+)?\n([\s\S]*?)```/g);
  return <div className="markdown">{parts.map((part, index) => index % 2 === 1 ? <pre key={index}><button type="button" onClick={() => void navigator.clipboard.writeText(part)}>Copiar</button><code>{part}</code></pre> : part.split("\n").map((line, lineIndex) => line.startsWith("### ") ? <h3 key={`${index}-${lineIndex}`}>{inlineMarkdown(line.slice(4))}</h3> : line.startsWith("## ") ? <h2 key={`${index}-${lineIndex}`}>{inlineMarkdown(line.slice(3))}</h2> : line.startsWith("# ") ? <h1 key={`${index}-${lineIndex}`}>{inlineMarkdown(line.slice(2))}</h1> : line.startsWith("- ") ? <li key={`${index}-${lineIndex}`}>{inlineMarkdown(line.slice(2))}</li> : <div key={`${index}-${lineIndex}`}>{inlineMarkdown(line)}</div>))}</div>;
}

function App(): JSX.Element {
  const [state, setState] = useState<SetupState>("loading");
  const [notice, setNotice] = useState("");
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [password, setPassword] = useState(""); const [token, setToken] = useState("");
  const [page, setPage] = useState<Page>("chat"); const [models, setModels] = useState<string[]>([]); const [model, setModel] = useState(""); const [catalog, setCatalog] = useState<ModelRecord[]>([]);
  const [conversations, setConversations] = useState<ConversationRecord[]>([]); const [conversationId, setConversationId] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const [prompt, setPrompt] = useState(""); const [isStreaming, setIsStreaming] = useState(false); const [streamingMessageId, setStreamingMessageId] = useState("");
  const [agents, setAgents] = useState<AgentRecord[]>([]); const [agentKey, setAgentKey] = useState(""); const [agentName, setAgentName] = useState(""); const [agentPrompt, setAgentPrompt] = useState("");
  const [workflows, setWorkflows] = useState<WorkflowRecord[]>([]); const [workflowName, setWorkflowName] = useState(""); const [workflowDetail, setWorkflowDetail] = useState<WorkflowDetail | null>(null); const [workflowVersionId, setWorkflowVersionId] = useState(""); const [workflowGraph, setWorkflowGraph] = useState("");
  const [plugins, setPlugins] = useState<PluginRecord[]>([]); const [pluginName, setPluginName] = useState(""); const [pluginVersion, setPluginVersion] = useState("0.1.0"); const [pluginDescription, setPluginDescription] = useState("");
  const [tasks, setTasks] = useState<TaskRecord[]>([]); const streamController = useRef<AbortController | null>(null);
  const [memory, setMemory] = useState<MemoryRecord[]>([]); const [memoryNamespace, setMemoryNamespace] = useState("general"); const [memoryContent, setMemoryContent] = useState(""); const [memoryQuery, setMemoryQuery] = useState("");
  const [audit, setAudit] = useState<AuditRecord[]>([]);
  const [system, setSystem] = useState<SystemStatus | null>(null);
  const [users, setUsers] = useState<UserRecord[]>([]);
  const auth = { Authorization: `Bearer ${token}` };

  useEffect(() => { fetch(`${API}/setup/status`).then(async response => { if (!response.ok) throw new Error(); setState((await response.json() as { setup_required: boolean }).setup_required ? "required" : "complete"); }).catch(() => { setState("error"); setNotice("No se pudo conectar con el Core."); }); }, []);
  async function loadCatalog(accessToken = token): Promise<void> { const headers = { Authorization: `Bearer ${accessToken}` }; await fetch(`${API}/models/sync`, { method: "POST", headers }); const response = await fetch(`${API}/models`, { headers }); if (response.ok) setCatalog((await response.json() as { items: ModelRecord[] }).items); }
  async function initialize(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response = await fetch(`${API}/setup/initialize`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, display_name: name, password }) }); if (!response.ok) return setNotice("No se pudo crear el administrador."); setState("complete"); setPassword(""); }
  async function login(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response = await fetch(`${API}/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) return setNotice("Credenciales inválidas."); const accessToken = (await response.json() as { access_token: string }).access_token; setToken(accessToken); setPassword(""); const headers = { Authorization: `Bearer ${accessToken}` }; const providers = await fetch(`${API}/providers/ollama/models`, { headers }); if (providers.ok) { const items = (await providers.json() as { items: { external_id: string; capabilities: string[] }[] }).items; const available = items.filter(item => item.capabilities.includes("completion")).map(item => item.external_id); setModels(available); setModel(available[0] ?? ""); } const history = await fetch(`${API}/conversations`, { headers }); if (history.ok) setConversations((await history.json() as { items: ConversationRecord[] }).items); await loadCatalog(accessToken); }
  async function openConversation(id: string): Promise<void> { const response = await fetch(`${API}/conversations/${id}/messages`, { headers: auth }); if (!response.ok) return; setConversationId(id); setMessages((await response.json() as { items: ChatMessage[] }).items); const record = conversations.find(item => item.id === id); if (record) setModel(record.model); }
  async function sendPrompt(text: string): Promise<void> { if (!text || !model || isStreaming) return; const headers = { "Content-Type": "application/json", ...auth }; let id = conversationId; if (!id) { const response = await fetch(`${API}/conversations`, { method: "POST", headers, body: JSON.stringify({ model }) }); if (!response.ok) return setNotice("No se pudo crear la conversación."); id = (await response.json() as { id: string }).id; setConversationId(id); setConversations(current => [{ id, title: "Nueva conversación", model }, ...current]); } setStreamingMessageId(""); setMessages(current => [...current, { role: "user", content: text }, { role: "assistant", content: "", status: "streaming" }]); const controller = new AbortController(); streamController.current = controller; setIsStreaming(true); try { const response = await fetch(`${API}/conversations/${id}/messages`, { method: "POST", headers, body: JSON.stringify({ content: text }), signal: controller.signal }); if (!response.ok || !response.body) throw new Error(); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); const frames = buffer.split("\n\n"); buffer = frames.pop() ?? ""; for (const frame of frames) { const data = frame.split("\n").find(line => line.startsWith("data: ")); if (!data) continue; if (frame.startsWith("event: message.started")) { const messageId = (JSON.parse(data.slice(6)) as { message_id: string }).message_id; setStreamingMessageId(messageId); setMessages(current => { const copy = [...current]; copy[copy.length - 1] = { ...copy[copy.length - 1], id: messageId }; return copy; }); } else if (frame.startsWith("event: message.delta")) { const delta = (JSON.parse(data.slice(6)) as { delta: string }).delta; setMessages(current => { const copy = [...current]; copy[copy.length - 1] = { ...copy[copy.length - 1], content: copy[copy.length - 1].content + delta }; return copy; }); } } } } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setNotice("La respuesta se interrumpió antes de completarse."); } finally { streamController.current = null; setStreamingMessageId(""); setIsStreaming(false); } }
  async function send(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const text = prompt; setPrompt(""); await sendPrompt(text); }
  async function regenerate(index: number): Promise<void> { const previous = [...messages.slice(0, index)].reverse().find(item => item.role === "user"); if (previous) await sendPrompt(previous.content); }
  async function cancelStreaming(): Promise<void> { if (conversationId && streamingMessageId) await fetch(`${API}/conversations/${conversationId}/messages/${streamingMessageId}/cancel`, { method: "POST", headers: auth }); streamController.current?.abort(); }
  async function loadAgents(): Promise<void> { const response = await fetch(`${API}/agents`, { headers: auth }); if (response.ok) setAgents((await response.json() as { items: AgentRecord[] }).items); }
  async function createAgent(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response = await fetch(`${API}/agents`, { method: "POST", headers: { "Content-Type": "application/json", ...auth }, body: JSON.stringify({ key: agentKey, name: agentName, system_prompt: agentPrompt, model: model || "llama3.2:3b" }) }); if (!response.ok) return setNotice("No se pudo crear el agente."); setAgentKey(""); setAgentName(""); setAgentPrompt(""); await loadAgents(); }
  async function loadTasks(): Promise<void> { const response = await fetch(`${API}/tasks`, { headers: auth }); if (response.ok) setTasks((await response.json() as { items: TaskRecord[] }).items); }
  async function taskAction(id: string, action: "cancel" | "retry"): Promise<void> { const response = await fetch(`${API}/tasks/${id}/${action}`, { method: "POST", headers: auth }); if (!response.ok) return setNotice("No se pudo actualizar la tarea."); await loadTasks(); }
  async function loadWorkflows(): Promise<void> { const response = await fetch(`${API}/workflows`, { headers: auth }); if (response.ok) setWorkflows((await response.json() as { items: WorkflowRecord[] }).items); }
  async function createWorkflow(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const graph = { nodes: [{ id: "input", type: "input" }, { id: "output", type: "output" }], edges: [{ from: "input", to: "output" }] }; const response = await fetch(`${API}/workflows`, { method: "POST", headers: { "Content-Type": "application/json", ...auth }, body: JSON.stringify({ name: workflowName, graph }) }); if (!response.ok) return setNotice("No se pudo crear el workflow."); setWorkflowName(""); await loadWorkflows(); }
  async function openWorkflow(id: string): Promise<void> { const response = await fetch(`${API}/workflows/${id}`, { headers: auth }); if (!response.ok) return setNotice("No se pudo abrir el workflow."); const detail = await response.json() as WorkflowDetail; setWorkflowDetail(detail); const version = detail.versions[0]; if (version) { setWorkflowVersionId(version.id); setWorkflowGraph(JSON.stringify(version.graph, null, 2)); } }
  async function saveWorkflow(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!workflowDetail) return; let graph: object; try { graph = JSON.parse(workflowGraph) as object; } catch { return setNotice("El grafo debe ser JSON válido."); } const response = await fetch(`${API}/workflows/${workflowDetail.id}/versions`, { method: "POST", headers: { "Content-Type": "application/json", ...auth }, body: JSON.stringify({ name: workflowDetail.name, description: workflowDetail.description, graph }) }); if (!response.ok) return setNotice("No se pudo guardar la versión."); await openWorkflow(workflowDetail.id); await loadWorkflows(); }
  async function workflowAction(action: "publish" | "run"): Promise<void> { if (!workflowDetail || !workflowVersionId) return; const endpoint = action === "publish" ? `${API}/workflows/${workflowDetail.id}/versions/${workflowVersionId}/publish` : `${API}/workflows/${workflowDetail.id}/versions/${workflowVersionId}/runs`; const response = await fetch(endpoint, { method: "POST", headers: action === "run" ? { "Content-Type": "application/json", ...auth } : auth, body: action === "run" ? JSON.stringify({ input: {} }) : undefined }); if (!response.ok) return setNotice("La versión debe estar publicada para ejecutarse."); if (action === "publish") await openWorkflow(workflowDetail.id); else setNotice(`Workflow en cola: ${(await response.json() as { run_id: string }).run_id}`); }
  async function loadPlugins(): Promise<void> { const response = await fetch(`${API}/plugins`, { headers: auth }); if (response.ok) setPlugins((await response.json() as { items: PluginRecord[] }).items); }
  async function registerPlugin(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response = await fetch(`${API}/plugins`, { method: "POST", headers: { "Content-Type": "application/json", ...auth }, body: JSON.stringify({ name: pluginName, version: pluginVersion, description: pluginDescription }) }); if (!response.ok) return setNotice("No se pudo registrar el plugin."); setPluginName(""); setPluginDescription(""); await loadPlugins(); }
  async function pluginAction(id: string, action: "enable" | "disable"): Promise<void> { const response = await fetch(`${API}/plugins/${id}/${action}`, { method: "POST", headers: auth }); if (!response.ok) return setNotice("No se pudo actualizar el plugin."); await loadPlugins(); }
  async function loadMemory(query = memoryQuery): Promise<void> { const params = new URLSearchParams(); if (query) params.set("query", query); const response = await fetch(`${API}/memory?${params.toString()}`, { headers: auth }); if (response.ok) setMemory((await response.json() as { items: MemoryRecord[] }).items); else setNotice("No se pudo cargar la memoria."); }
  async function createMemory(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const response = await fetch(`${API}/memory`, { method: "POST", headers: { "Content-Type": "application/json", ...auth }, body: JSON.stringify({ namespace: memoryNamespace, content: memoryContent }) }); if (!response.ok) return setNotice("No se pudo guardar la memoria."); setMemoryContent(""); await loadMemory(); }
  async function deleteMemory(id: string): Promise<void> { const response = await fetch(`${API}/memory/${id}`, { method: "DELETE", headers: auth }); if (!response.ok) return setNotice("No se pudo eliminar la memoria."); await loadMemory(); }
  async function loadAudit(): Promise<void> { const response = await fetch(`${API}/audit-events`, { headers: auth }); if (response.ok) setAudit((await response.json() as { items: AuditRecord[] }).items); else setNotice("No tenés permiso para ver la auditoría."); }
  async function loadSystem(): Promise<void> { const response = await fetch(`${API}/system/status`, { headers: auth }); if (response.ok) setSystem(await response.json() as SystemStatus); else setNotice("No se pudo consultar el estado del sistema."); }
  async function loadUsers(): Promise<void> { const response = await fetch(`${API}/access/users`, { headers: auth }); if (response.ok) setUsers((await response.json() as { items: UserRecord[] }).items); else setNotice("No tenés permiso para ver usuarios."); }

  const navigation = <aside><strong>ALSEMA</strong><small>AI CORE</small><nav aria-label="Navegación principal"><button aria-current={page === "home" ? "page" : undefined} onClick={() => setPage("home")}>Inicio</button><button aria-current={page === "chat" ? "page" : undefined} onClick={() => setPage("chat")}>Chat</button><button aria-current={page === "models" ? "page" : undefined} onClick={() => setPage("models")}>Modelos</button><button aria-current={page === "agents" ? "page" : undefined} onClick={() => { setPage("agents"); void loadAgents(); }}>Agentes</button><button aria-current={page === "workflows" ? "page" : undefined} onClick={() => { setPage("workflows"); void loadWorkflows(); }}>Workflows</button><button aria-current={page === "plugins" ? "page" : undefined} onClick={() => { setPage("plugins"); void loadPlugins(); }}>Plugins</button><button aria-current={page === "tasks" ? "page" : undefined} onClick={() => { setPage("tasks"); void loadTasks(); }}>Tareas</button><button aria-current={page === "memory" ? "page" : undefined} onClick={() => { setPage("memory"); void loadMemory(); }}>Memoria</button><button aria-current={page === "audit" ? "page" : undefined} onClick={() => { setPage("audit"); void loadAudit(); }}>Auditoría</button><button aria-current={page === "users" ? "page" : undefined} onClick={() => { setPage("users"); void loadUsers(); }}>Usuarios</button><button aria-current={page === "system" ? "page" : undefined} onClick={() => { setPage("system"); void loadSystem(); }}>Sistema</button></nav></aside>;

  if (token && page === "memory") return <main>{navigation}<section><p>MEMORIA</p><h1>Memoria persistente</h1><form className="card" onSubmit={createMemory}><label>Namespace<input value={memoryNamespace} onChange={event => setMemoryNamespace(event.target.value)} required /></label><label>Contenido<textarea value={memoryContent} onChange={event => setMemoryContent(event.target.value)} required /></label><button>Guardar memoria</button></form><form className="compact" onSubmit={event => { event.preventDefault(); void loadMemory(); }}><input value={memoryQuery} onChange={event => setMemoryQuery(event.target.value)} placeholder="Buscar en memoria" /><button>Buscar</button></form><div className="catalog">{memory.map(item => <article key={item.id}><strong>{item.namespace} · {item.scope}</strong><span>{item.content}</span><small>{new Date(item.created_at).toLocaleString()}</small><button onClick={() => void deleteMemory(item.id)}>Eliminar</button></article>)}</div><span className="error">{notice}</span></section></main>;
  if (token && page === "audit") return <main>{navigation}<section><p>AUDITORÍA</p><h1>Eventos del sistema</h1><button onClick={() => void loadAudit()}>Actualizar</button><div className="catalog">{audit.map(item => <article key={item.id}><strong>{item.action}</strong><span>{item.target_type} · {item.target_id} · {item.outcome}</span><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div><span className="error">{notice}</span></section></main>;
  if (token && page === "system") return <main>{navigation}<section><p>SISTEMA</p><h1>Estado del Core</h1><button onClick={() => void loadSystem()}>Actualizar</button>{system && <div className="card"><strong>Core {system.version}</strong><span>Ollama: {system.ollama.status}</span><span>{system.ollama.model_count} modelos disponibles</span><small>{system.ollama.detail}</small></div>}<span className="error">{notice}</span></section></main>;
  if (token && page === "users") return <main>{navigation}<section><p>USUARIOS</p><h1>Acceso y roles</h1><button onClick={() => void loadUsers()}>Actualizar</button><div className="catalog">{users.map(item => <article key={item.id}><strong>{item.display_name}</strong><span>{item.email} · {item.status}</span><small>{item.roles.join(", ")}</small></article>)}</div><span className="error">{notice}</span></section></main>;
  if (state === "loading") return <main><section><p>SISTEMA</p><h1>Comprobando instalación…</h1></section></main>;
  if (state === "error") return <main><section><p>SISTEMA</p><h1>No se pudo conectar</h1><span className="error">{notice}</span></section></main>;
  if (state === "required") return <main><aside><strong>ALSEMA</strong><small>AI CORE</small></aside><section><p>SISTEMA</p><h1>Configuración inicial</h1><form className="card" onSubmit={initialize}><label>Nombre<input value={name} onChange={event => setName(event.target.value)} required /></label><label>Correo<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Contraseña<input type="password" minLength={12} value={password} onChange={event => setPassword(event.target.value)} required /></label><button>Crear administrador</button><span className="error">{notice}</span></form></section></main>;
  if (!token) return <main><aside><strong>ALSEMA</strong><small>AI CORE</small></aside><section><p>SISTEMA</p><h1>Iniciar sesión</h1><form className="card" onSubmit={login}><label>Correo<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Contraseña<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label><button>Ingresar</button><span className="error">{notice}</span></form></section></main>;
  if (page === "home") return <main>{navigation}<section><p>INICIO</p><h1>ALSEMA AI CORE</h1><div className="card"><strong>Plataforma local disponible</strong><span>{catalog.length} modelos detectados.</span><button onClick={() => setPage("chat")}>Abrir Chat</button></div></section></main>;
  if (page === "models") return <main>{navigation}<section><p>MODELOS</p><h1>Catálogo local</h1><button onClick={() => void loadCatalog()}>Sincronizar con Ollama</button><div className="catalog">{catalog.map(item => <article key={item.id}><strong>{item.name}</strong><span>{item.provider} · {item.status}</span><small>{item.model} · {item.metadata.size_bytes ? `${(item.metadata.size_bytes / 1_000_000_000).toFixed(1)} GB` : "tamaño no disponible"}</small></article>)}</div></section></main>;
  if (page === "agents") return <main>{navigation}<section><p>AGENTES</p><h1>Agentes</h1><form className="card" onSubmit={createAgent}><label>Clave<input value={agentKey} onChange={event => setAgentKey(event.target.value)} pattern="[a-z0-9-]{3,120}" required /></label><label>Nombre<input value={agentName} onChange={event => setAgentName(event.target.value)} required /></label><label>Prompt del sistema<textarea value={agentPrompt} onChange={event => setAgentPrompt(event.target.value)} required /></label><button>Crear borrador</button></form><button onClick={() => void loadAgents()}>Actualizar</button><div className="catalog">{agents.map(item => <article key={item.id}><strong>{item.name}</strong><span>{item.key} · {item.status}</span></article>)}</div><span className="error">{notice}</span></section></main>;
  if (page === "workflows") return <main>{navigation}<section><p>WORKFLOWS</p><h1>Workflows</h1><form className="card" onSubmit={createWorkflow}><label>Nombre<input value={workflowName} onChange={event => setWorkflowName(event.target.value)} required /></label><button>Crear workflow manual</button></form><div className="catalog">{workflows.map(item => <article key={item.id}><strong>{item.name}</strong><span>{item.status}</span><button onClick={() => void openWorkflow(item.id)}>Abrir</button></article>)}</div>{workflowDetail && <form className="card" onSubmit={saveWorkflow}><h2>{workflowDetail.name}</h2><select value={workflowVersionId} onChange={event => { const version = workflowDetail.versions.find(item => item.id === event.target.value); setWorkflowVersionId(event.target.value); if (version) setWorkflowGraph(JSON.stringify(version.graph, null, 2)); }}>{workflowDetail.versions.map(version => <option key={version.id} value={version.id}>v{version.number} · {version.status}</option>)}</select><textarea value={workflowGraph} onChange={event => setWorkflowGraph(event.target.value)} required /><button>Guardar nueva versión</button><button type="button" onClick={() => void workflowAction("publish")}>Publicar</button><button type="button" onClick={() => void workflowAction("run")}>Ejecutar</button></form>}<span className="error">{notice}</span></section></main>;
  if (page === "plugins") return <main>{navigation}<section><p>PLUGINS</p><h1>Plugins</h1><form className="card" onSubmit={registerPlugin}><label>Nombre<input value={pluginName} onChange={event => setPluginName(event.target.value)} pattern="[a-z0-9-]{3,120}" required /></label><label>Versión<input value={pluginVersion} onChange={event => setPluginVersion(event.target.value)} pattern="[0-9]+\\.[0-9]+\\.[0-9]+" required /></label><label>Descripción<textarea value={pluginDescription} onChange={event => setPluginDescription(event.target.value)} /></label><button>Registrar plugin</button></form><div className="catalog">{plugins.map(item => <article key={item.id}><strong>{item.name}</strong><span>{item.version} · {item.status}</span><button onClick={() => void pluginAction(item.id, item.status === "enabled" ? "disable" : "enable")}>{item.status === "enabled" ? "Desactivar" : "Activar"}</button></article>)}</div><span className="error">{notice}</span></section></main>;
  if (page === "tasks") return <main>{navigation}<section><p>TAREAS</p><h1>Actividad en segundo plano</h1><button onClick={() => void loadTasks()}>Actualizar</button><div className="catalog">{tasks.map(item => <article key={item.id}><strong>{item.type}</strong><span>{item.status} · {item.progress.message}</span>{item.status === "running" && <button onClick={() => void taskAction(item.id, "cancel")}>Cancelar</button>}{["failed", "cancelled"].includes(item.status) && <button onClick={() => void taskAction(item.id, "retry")}>Reintentar</button>}</article>)}</div></section></main>;
  return <main>{navigation}<section><p>CHAT</p><h1>Conversación local</h1><select value={conversationId} onChange={event => { if (event.target.value) void openConversation(event.target.value); }}><option value="">Nueva conversación</option>{conversations.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><div className="chat">{messages.length === 0 ? <span>Elegí un modelo y enviá tu primer mensaje.</span> : messages.map((item, index) => <article className={item.role} key={item.id ?? index}><b>{item.role === "user" ? "Vos" : "ALSEMA"}</b><MarkdownMessage content={item.content} />{item.role === "assistant" && !isStreaming && <button type="button" onClick={() => void regenerate(index)}>Regenerar</button>}</article>)}</div><form className="chat-input" onSubmit={send}><select value={model} onChange={event => setModel(event.target.value)}>{models.map(item => <option key={item}>{item}</option>)}</select><input value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Escribí un mensaje" required disabled={isStreaming} /><button disabled={isStreaming}>{isStreaming ? "Generando…" : "Enviar"}</button>{isStreaming && <button type="button" onClick={() => void cancelStreaming()}>Cancelar</button>}</form><span className="error">{notice}</span></section></main>;
}

createRoot(document.getElementById("root")!).render(<App/>);
