from typing import Any

TEMPLATE_FAMILY = "instanews_social_publication"
TEMPLATE_VERSION = "1.2.0"

OUTPUT_TEMPLATES: dict[str, dict[str, Any]] = {
    "story": {
        "key": "instanews-social-story",
        "name": "INSTANEWS Historia 9x16",
        "format": "Historia",
        "width": 1080,
        "height": 1920,
        "safe_area": {"top": 160, "bottom": 220, "left": 80, "right": 80},
        "logo": {"badge_size": 170, "logo_max_width": 120, "margin_top": 160, "margin_right": 80},
        "content": {
            "margin_bottom": 220,
            "category_font_size": 28,
            "category_padding_x": 20,
            "category_padding_y": 10,
            "category_radius": 12,
            "category_gap": 12,
            "title_max": 82,
            "title_min": 58,
            "title_lines": 4,
            "title_line_height": 0.98,
            "title_margin_top": 34,
            "summary_max": 38,
            "summary_min": 28,
            "summary_lines": 5,
            "summary_line_height": 1.22,
            "summary_margin_top": 28,
        },
    },
    "feed_4_5": {
        "key": "instanews-social-feed-4x5",
        "name": "INSTANEWS Feed 4x5",
        "format": "Instagram",
        "width": 1080,
        "height": 1350,
        "safe_area": {"top": 80, "bottom": 100, "left": 70, "right": 70},
        "logo": {"badge_size": 140, "logo_max_width": 100, "margin_top": 80, "margin_right": 70},
        "content": {
            "margin_bottom": 95,
            "category_font_size": 24,
            "category_padding_x": 18,
            "category_padding_y": 9,
            "category_radius": 11,
            "category_gap": 12,
            "title_max": 68,
            "title_min": 48,
            "title_lines": 3,
            "title_line_height": 1.0,
            "title_margin_top": 28,
            "summary_max": 32,
            "summary_min": 24,
            "summary_lines": 4,
            "summary_line_height": 1.22,
            "summary_margin_top": 22,
        },
    },
}


def editor_document(output: str) -> dict[str, Any]:
    template = OUTPUT_TEMPLATES[output]
    return {
        "id": template["key"],
        "name": template["name"],
        "format": template["format"],
        "width": template["width"],
        "height": template["height"],
        "background": "#07111f",
        "instanews": {**template, "output": output, "template_family": TEMPLATE_FAMILY, "template_version": TEMPLATE_VERSION},
        "layers": [
            {
                "id": f"{output}-image",
                "type": "shape",
                "shape": "rectangle",
                "name": "Imagen principal dinámica",
                "x": 0,
                "y": 0,
                "width": template["width"],
                "height": template["height"],
                "rotation": 0,
                "opacity": 1,
                "visible": True,
                "locked": True,
                "z": 1,
                "fill": "#07111f",
                "stroke": "#07111f",
                "strokeWidth": 0,
                "borderRadius": 0,
            },
            {
                "id": f"{output}-title",
                "type": "text",
                "name": "Título dinámico",
                "x": template["safe_area"]["left"],
                "y": round(template["height"] * 0.62),
                "width": template["width"] - template["safe_area"]["left"] - template["safe_area"]["right"],
                "height": 260,
                "rotation": 0,
                "opacity": 1,
                "visible": True,
                "locked": False,
                "z": 2,
                "text": "TÍTULO DE LA NOTICIA",
                "fontFamily": "Montserrat",
                "fontSize": template["content"]["title_max"],
                "fontWeight": 800,
                "color": "#ffffff",
                "textAlign": "left",
                "lineHeight": template["content"]["title_line_height"],
                "letterSpacing": 0,
            },
            {
                "id": f"{output}-summary",
                "type": "text",
                "name": "Bajada dinámica",
                "x": template["safe_area"]["left"],
                "y": round(template["height"] * 0.82),
                "width": template["width"] - template["safe_area"]["left"] - template["safe_area"]["right"],
                "height": 220,
                "rotation": 0,
                "opacity": 1,
                "visible": True,
                "locked": False,
                "z": 3,
                "text": "Bajada informativa de la noticia.",
                "fontFamily": "Montserrat",
                "fontSize": template["content"]["summary_max"],
                "fontWeight": 500,
                "color": "#ffffff",
                "textAlign": "left",
                "lineHeight": template["content"]["summary_line_height"],
                "letterSpacing": 0,
            },
        ],
    }
