import { toPng } from "html-to-image";
import { useEffect, useMemo, useRef, useState } from "react";

const API = "http://localhost:8000/api/v1/creative";
const FONTS = ["Inter", "Manrope", "Montserrat", "Poppins", "DM Sans", "Space Grotesk", "Outfit", "Plus Jakarta Sans", "Urbanist", "Sora", "Archivo", "Barlow", "Rubik", "Work Sans", "Lato", "Nunito Sans", "Open Sans", "Roboto", "Roboto Condensed", "Oswald", "Bebas Neue", "Anton", "League Spartan", "Archivo Black", "Raleway", "Fira Sans", "Titillium Web", "Exo 2", "Orbitron"];
const FORMATS = { Instagram: { width: 1080, height: 1350 }, Cuadrado: { width: 1080, height: 1080 }, Historia: { width: 1080, height: 1920 }, Horizontal: { width: 1600, height: 900 } } as const;

type LayerType = "text" | "image" | "shape";
export type EditorLayer = { id: string; type: LayerType; name: string; x: number; y: number; width: number; height: number; rotation: number; opacity: number; visible: boolean; locked: boolean; z: number; text?: string; fontFamily?: string; fontSize?: number; fontWeight?: number; color?: string; textAlign?: "left" | "center" | "right"; lineHeight?: number; letterSpacing?: number; src?: string; fit?: "contain" | "cover"; fill?: string; stroke?: string; strokeWidth?: number; borderRadius?: number; shape?: "rectangle" | "circle" | "line" };
export type EditorDocument = { id: string; name: string; format: keyof typeof FORMATS; width: number; height: number; background: string; layers: EditorLayer[] };
export type EditorTemplateRecord = { id: string; key: string; name: string; description: string; document: EditorDocument; version: number; status: string; created_at: string };
type PointerAction = { kind: "move" | "resize"; id: string; clientX: number; clientY: number; origin: EditorLayer };

const uid = (): string => crypto.randomUUID();
const starter = (): EditorDocument => ({ id: uid(), name: "Plantilla sin nombre", format: "Instagram", ...FORMATS.Instagram, background: "#07111f", layers: [
  { id: uid(), type: "shape", shape: "rectangle", name: "Acento superior", x: 72, y: 72, width: 300, height: 18, rotation: 0, opacity: 1, visible: true, locked: false, z: 1, fill: "#00C2FF", stroke: "#00C2FF", strokeWidth: 0, borderRadius: 12 },
  { id: uid(), type: "text", name: "Título principal", x: 72, y: 850, width: 720, height: 180, rotation: 0, opacity: 1, visible: true, locked: false, z: 2, text: "TÍTULO DEL PRODUCTO", fontFamily: "Space Grotesk", fontSize: 74, fontWeight: 800, color: "#ffffff", textAlign: "left", lineHeight: 1, letterSpacing: -2 },
  { id: uid(), type: "text", name: "Llamado a la acción", x: 72, y: 1080, width: 330, height: 72, rotation: 0, opacity: 1, visible: true, locked: false, z: 3, text: "Ver producto", fontFamily: "Inter", fontSize: 30, fontWeight: 800, color: "#07111f", textAlign: "center", lineHeight: 1, letterSpacing: 0, fill: "#00C2FF", borderRadius: 16 },
] });

function download(url: string, name: string): void { const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
function slug(value: string): string { return value.toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || `template-${Date.now()}`; }

export function CreativeTemplateEditor({ token, records, refresh }: { token: string; records: EditorTemplateRecord[]; refresh: () => Promise<void> }): JSX.Element {
  const [documentState, setDocumentState] = useState<EditorDocument>(starter);
  const [selected, setSelected] = useState<string | null>(documentState.layers[1].id);
  const [zoom, setZoom] = useState(.42); const [grid, setGrid] = useState(true); const [status, setStatus] = useState("Lista para diseñar");
  const [history, setHistory] = useState<EditorDocument[]>([]); const [future, setFuture] = useState<EditorDocument[]>([]);
  const pointer = useRef<PointerAction | null>(null); const canvas = useRef<HTMLDivElement | null>(null); const upload = useRef<HTMLInputElement | null>(null); const importRef = useRef<HTMLInputElement | null>(null);
  const active = documentState.layers.find(layer => layer.id === selected) ?? null;
  const ordered = useMemo(() => [...documentState.layers].sort((a, b) => a.z - b.z), [documentState.layers]);
  const remember = (): void => { setHistory(items => [...items.slice(-39), structuredClone(documentState)]); setFuture([]); };
  const update = (patch: Partial<EditorLayer>, commit = false): void => { if (!selected) return; if (commit) remember(); setDocumentState(value => ({ ...value, layers: value.layers.map(layer => layer.id === selected ? { ...layer, ...patch } : layer) })); };
  const add = (layer: EditorLayer): void => { remember(); setDocumentState(value => ({ ...value, layers: [...value.layers, layer] })); setSelected(layer.id); };
  const addText = (kind: "title" | "body"): void => add({ id: uid(), type: "text", name: kind === "title" ? "Título" : "Texto", x: 120, y: kind === "title" ? 240 : 470, width: 700, height: kind === "title" ? 170 : 100, rotation: 0, opacity: 1, visible: true, locked: false, z: documentState.layers.length + 1, text: kind === "title" ? "NUEVO TÍTULO" : "Escribí tu texto aquí", fontFamily: kind === "title" ? "Space Grotesk" : "Inter", fontSize: kind === "title" ? 76 : 34, fontWeight: kind === "title" ? 800 : 500, color: "#ffffff", textAlign: "left", lineHeight: 1.05, letterSpacing: 0 });
  const addShape = (shape: EditorLayer["shape"]): void => add({ id: uid(), type: "shape", shape, name: shape === "circle" ? "Círculo" : shape === "line" ? "Línea" : "Rectángulo", x: 180, y: 300, width: shape === "line" ? 550 : 260, height: shape === "line" ? 8 : 180, rotation: 0, opacity: 1, visible: true, locked: false, z: documentState.layers.length + 1, fill: "#00C2FF", stroke: "#00C2FF", strokeWidth: 0, borderRadius: shape === "circle" ? 999 : 18 });
  const remove = (): void => { if (!selected) return; remember(); setDocumentState(value => ({ ...value, layers: value.layers.filter(layer => layer.id !== selected) })); setSelected(null); };
  const duplicate = (): void => { if (!active) return; const copy = { ...structuredClone(active), id: uid(), name: `${active.name} copia`, x: active.x + 24, y: active.y + 24, z: documentState.layers.length + 1 }; add(copy); };
  const moveZ = (direction: number): void => { if (!active) return; remember(); const sorted = [...ordered]; const index = sorted.findIndex(layer => layer.id === active.id); const target = Math.max(0, Math.min(sorted.length - 1, index + direction)); [sorted[index], sorted[target]] = [sorted[target], sorted[index]]; setDocumentState(value => ({ ...value, layers: sorted.map((layer, position) => ({ ...layer, z: position + 1 })) })); };
  const undo = (): void => { const previous = history.at(-1); if (!previous) return; setFuture(items => [structuredClone(documentState), ...items]); setDocumentState(previous); setHistory(items => items.slice(0, -1)); setSelected(null); };
  const redo = (): void => { const next = future[0]; if (!next) return; setHistory(items => [...items, structuredClone(documentState)]); setDocumentState(next); setFuture(items => items.slice(1)); setSelected(null); };
  useEffect(() => { const handler = (event: KeyboardEvent): void => { const inputFocused = ["INPUT", "TEXTAREA"].includes(document.activeElement?.tagName ?? ""); if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "d") { event.preventDefault(); duplicate(); } else if (event.key === "Delete" && !inputFocused) remove(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  const pointerMove = (event: React.PointerEvent): void => { const action = pointer.current; if (!action) return; const dx = (event.clientX - action.clientX) / zoom; const dy = (event.clientY - action.clientY) / zoom; setDocumentState(value => ({ ...value, layers: value.layers.map(layer => layer.id !== action.id ? layer : action.kind === "move" ? { ...layer, x: Math.round(action.origin.x + dx), y: Math.round(action.origin.y + dy) } : { ...layer, width: Math.max(30, Math.round(action.origin.width + dx)), height: Math.max(20, Math.round(action.origin.height + dy)) }) })); };
  const pointerUp = (): void => { pointer.current = null; };
  const uploadImage = (file: File): void => { if (file.size > 5_000_000) { setStatus("La imagen supera el límite de 5 MB"); return; } const reader = new FileReader(); reader.onload = () => { const source = String(reader.result); const image = new Image(); image.onload = () => { const width = 520; const height = Math.round(width / (image.naturalWidth / image.naturalHeight)); add({ id: uid(), type: "image", name: file.name, x: 220, y: 180, width, height, rotation: 0, opacity: 1, visible: true, locked: false, z: documentState.layers.length + 1, src: source, fit: "contain", borderRadius: 0 }); setStatus("Imagen agregada y persistirá con la plantilla"); }; image.src = source; }; reader.readAsDataURL(file); };
  const save = async (publish = true): Promise<void> => { if (!documentState.name.trim()) { setStatus("Poné un nombre antes de guardar"); return; } setStatus("Guardando versión…"); const response = await fetch(`${API}/templates`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ key: slug(documentState.name), name: documentState.name, description: "Plantilla creada en el editor profesional ALSEMA", document: documentState, publish }) }); if (!response.ok) { setStatus("No se pudo guardar la plantilla"); return; } await refresh(); setStatus("Nueva versión guardada"); };
  const load = (record: EditorTemplateRecord): void => { remember(); setDocumentState(record.document); setSelected(null); setStatus(`Plantilla “${record.name}” abierta`); };
  const deleteSaved = async (record: EditorTemplateRecord): Promise<void> => { if (!window.confirm(`¿Eliminar la versión ${record.version} de “${record.name}”?`)) return; const response = await fetch(`${API}/templates/${record.id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) { await refresh(); setStatus("Versión eliminada"); } else setStatus("No se pudo eliminar la versión"); };
  const exportJson = (): void => download(URL.createObjectURL(new Blob([JSON.stringify(documentState, null, 2)], { type: "application/json" })), `${documentState.name}.json`);
  const importJson = async (file: File): Promise<void> => { try { const value = JSON.parse(await file.text()) as EditorDocument; if (!Array.isArray(value.layers) || !value.width || !value.height) throw new Error(); remember(); setDocumentState({ ...value, id: uid(), name: `${value.name} importada` }); setSelected(null); setStatus("Plantilla importada"); } catch { setStatus("Ese JSON no es una plantilla válida"); } };
  const exportPng = async (): Promise<void> => { if (!canvas.current) return; const restoreGrid = grid; setSelected(null); setGrid(false); setStatus("Generando PNG…"); await new Promise(resolve => window.setTimeout(resolve, 80)); const url = await toPng(canvas.current, { width: documentState.width, height: documentState.height, pixelRatio: 1, cacheBust: true, style: { transform: "none" } }); download(url, `${documentState.name}.png`); setGrid(restoreGrid); setStatus("PNG exportado"); };
  const newDocument = (): void => { remember(); const value = starter(); setDocumentState(value); setSelected(value.layers[1].id); setStatus("Nueva plantilla"); };
  const changeFormat = (format: keyof typeof FORMATS): void => { remember(); setDocumentState(value => ({ ...value, format, ...FORMATS[format] })); };

  return <div className="migrated-editor">
    <header className="migrated-editor-header"><div><span className="creative-kicker">DISEÑO / PLANTILLAS</span><h2>Editor profesional</h2></div><div><button type="button" onClick={newDocument}>Nueva</button><button type="button" onClick={undo} disabled={!history.length}>↶</button><button type="button" onClick={redo} disabled={!future.length}>↷</button><button type="button" className="primary" onClick={() => void save(true)}>Guardar plantilla</button><button type="button" onClick={() => void exportPng()}>Exportar PNG</button></div></header>
    <div className="migrated-document-bar"><input value={documentState.name} onChange={event => setDocumentState(value => ({ ...value, name: event.target.value }))} /><select value={documentState.format} onChange={event => changeFormat(event.target.value as keyof typeof FORMATS)}>{Object.keys(FORMATS).map(format => <option key={format}>{format}</option>)}</select><label>Zoom<input type="range" min=".25" max=".7" step=".05" value={zoom} onChange={event => setZoom(Number(event.target.value))} /></label><button type="button" className={grid ? "on" : ""} onClick={() => setGrid(value => !value)}>Cuadrícula</button><span>{documentState.width} × {documentState.height}px</span></div>
    <div className="migrated-editor-workspace">
      <div className="migrated-toolbox"><span className="creative-kicker">AGREGAR</span><button type="button" onClick={() => addText("title")}><b>T</b><span>Título</span></button><button type="button" onClick={() => addText("body")}><b>Tt</b><span>Texto</span></button><button type="button" onClick={() => upload.current?.click()}><b>▧</b><span>Imagen</span></button><button type="button" onClick={() => addShape("rectangle")}><b>□</b><span>Rectángulo</span></button><button type="button" onClick={() => addShape("circle")}><b>○</b><span>Círculo</span></button><button type="button" onClick={() => addShape("line")}><b>╱</b><span>Línea</span></button><input ref={upload} hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={event => event.target.files?.[0] && uploadImage(event.target.files[0])} /><hr /><button type="button" onClick={exportJson}><b>↓</b><span>JSON</span></button><button type="button" onClick={() => importRef.current?.click()}><b>↑</b><span>Importar</span></button><input ref={importRef} hidden type="file" accept="application/json" onChange={event => event.target.files?.[0] && void importJson(event.target.files[0])} /></div>
      <div className="migrated-stage" onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><div className="migrated-stage-scroll"><div style={{ width: documentState.width * zoom, height: documentState.height * zoom }}><div ref={canvas} className={`migrated-design-canvas ${grid ? "with-grid" : ""}`} style={{ width: documentState.width, height: documentState.height, background: documentState.background, transform: `scale(${zoom})` }} onPointerDown={() => setSelected(null)}>{ordered.map(layer => <LayerView key={layer.id} layer={layer} selected={selected === layer.id} choose={() => setSelected(layer.id)} begin={(kind, event) => { if (layer.locked) return; event.stopPropagation(); setSelected(layer.id); remember(); pointer.current = { kind, id: layer.id, clientX: event.clientX, clientY: event.clientY, origin: structuredClone(layer) }; event.currentTarget.setPointerCapture(event.pointerId); }} />)}</div></div></div></div>
      <div className="migrated-right-panel"><div className="migrated-panel-tabs"><b>PROPIEDADES</b><span>{active?.type.toUpperCase() ?? "LIENZO"}</span></div>{active ? <Properties layer={active} update={update} /> : <div className="migrated-properties"><Color label="Color de fondo" value={documentState.background} change={background => { remember(); setDocumentState(value => ({ ...value, background })); }} /></div>}<div className="migrated-quick-actions"><button type="button" disabled={!active} onClick={duplicate}>Duplicar</button><button type="button" disabled={!active} onClick={() => moveZ(1)}>Subir</button><button type="button" disabled={!active} onClick={() => moveZ(-1)}>Bajar</button><button type="button" className="danger" disabled={!active} onClick={remove}>Eliminar</button></div><span className="creative-kicker">CAPAS</span><div className="migrated-layers">{[...ordered].reverse().map(layer => <button type="button" className={selected === layer.id ? "selected" : ""} onClick={() => setSelected(layer.id)} key={layer.id}><i>{layer.type === "text" ? "T" : layer.type === "image" ? "▧" : "◇"}</i><span>{layer.name}</span><em onClick={event => { event.stopPropagation(); setDocumentState(value => ({ ...value, layers: value.layers.map(item => item.id === layer.id ? { ...item, visible: !item.visible } : item) })); }}>{layer.visible ? "●" : "○"}</em><em onClick={event => { event.stopPropagation(); setDocumentState(value => ({ ...value, layers: value.layers.map(item => item.id === layer.id ? { ...item, locked: !item.locked } : item) })); }}>{layer.locked ? "🔒" : "·"}</em></button>)}</div></div>
    </div>
    <div className="migrated-template-library"><div><h3>Biblioteca versionada</h3><p>{records.length} versiones guardadas en PostgreSQL</p></div><div>{records.map(record => <article key={record.id}><div style={{ background: record.document.background }}><span>{record.document.layers.length} capas</span></div><b>{record.name}</b><small>v{record.version} · {record.status}</small><button type="button" onClick={() => load(record)}>Abrir</button><button type="button" className="danger" onClick={() => void deleteSaved(record)}>Eliminar</button></article>)}</div></div>
    <footer className="migrated-editor-status">{status}<span>Ctrl+Z deshacer · Ctrl+D duplicar · Supr eliminar</span></footer>
  </div>;
}

function LayerView({ layer, selected, choose, begin }: { layer: EditorLayer; selected: boolean; choose: () => void; begin: (kind: "move" | "resize", event: React.PointerEvent<HTMLDivElement>) => void }): JSX.Element {
  const style: React.CSSProperties = { left: layer.x, top: layer.y, width: layer.width, height: layer.height, transform: `rotate(${layer.rotation}deg)`, opacity: layer.opacity, zIndex: layer.z, display: layer.visible ? "block" : "none" };
  return <div className={`migrated-editor-layer ${selected ? "selected " : ""}${layer.locked ? "locked" : ""}`} style={style} onPointerDown={event => { choose(); begin("move", event); }}>{layer.type === "text" ? <div className="migrated-layer-text" style={{ fontFamily: `"${layer.fontFamily}",sans-serif`, fontSize: layer.fontSize, fontWeight: layer.fontWeight, color: layer.color, textAlign: layer.textAlign, lineHeight: layer.lineHeight, letterSpacing: layer.letterSpacing, background: layer.fill, borderRadius: layer.borderRadius, WebkitTextStroke: layer.strokeWidth ? `${layer.strokeWidth}px ${layer.stroke}` : undefined }}>{layer.text}</div> : layer.type === "image" ? <img src={layer.src} style={{ objectFit: layer.fit, borderRadius: layer.borderRadius }} /> : <div className={`migrated-layer-shape ${layer.shape ?? ""}`} style={{ background: layer.fill, borderColor: layer.stroke, borderWidth: layer.strokeWidth, borderRadius: layer.borderRadius }} />}{selected && !layer.locked && <div className="migrated-resize-handle" onPointerDown={event => begin("resize", event)} />}</div>;
}

function Properties({ layer, update }: { layer: EditorLayer; update: (patch: Partial<EditorLayer>, commit?: boolean) => void }): JSX.Element {
  const number = (label: string, key: keyof EditorLayer, min: number, max: number, step = 1): JSX.Element => <label>{label}<input type="number" min={min} max={max} step={step} value={Number(layer[key] ?? 0)} onChange={event => update({ [key]: Number(event.target.value) }, true)} /></label>;
  return <div className="migrated-properties"><label>Nombre de capa<input value={layer.name} onChange={event => update({ name: event.target.value }, true)} /></label>{layer.type === "text" && <><label>Texto<textarea rows={4} value={layer.text} onChange={event => update({ text: event.target.value }, true)} /></label><label>Tipografía<select value={layer.fontFamily} onChange={event => update({ fontFamily: event.target.value }, true)}>{FONTS.map(font => <option style={{ fontFamily: font }} key={font}>{font}</option>)}</select></label><div className="migrated-property-grid">{number("Tamaño", "fontSize", 8, 240)}<label>Grosor<select value={layer.fontWeight} onChange={event => update({ fontWeight: Number(event.target.value) }, true)}>{[300, 400, 500, 600, 700, 800, 900].map(weight => <option key={weight}>{weight}</option>)}</select></label>{number("Interletrado", "letterSpacing", -10, 30, .5)}{number("Interlineado", "lineHeight", .7, 2, .05)}</div><div className="migrated-align"><button type="button" onClick={() => update({ textAlign: "left" }, true)}>≡</button><button type="button" onClick={() => update({ textAlign: "center" }, true)}>≡</button><button type="button" onClick={() => update({ textAlign: "right" }, true)}>≡</button></div><Color label="Color del texto" value={layer.color ?? "#ffffff"} change={color => update({ color }, true)} /></>}{layer.type === "image" && <><label>Ajuste<select value={layer.fit} onChange={event => update({ fit: event.target.value as EditorLayer["fit"] }, true)}><option value="contain">Completa</option><option value="cover">Rellenar marco</option></select></label>{number("Esquinas", "borderRadius", 0, 500)}</>}{layer.type === "shape" && <><Color label="Relleno" value={layer.fill ?? "#00C2FF"} change={fill => update({ fill }, true)} /><div className="migrated-property-grid"><Color label="Borde" value={layer.stroke ?? "#00C2FF"} change={stroke => update({ stroke }, true)} />{number("Grosor", "strokeWidth", 0, 30)}</div>{number("Esquinas", "borderRadius", 0, 500)}</>}<h4>Transformar</h4><div className="migrated-property-grid">{number("X", "x", -2000, 3000)}{number("Y", "y", -2000, 3000)}{number("Ancho", "width", 10, 3000)}{number("Alto", "height", 10, 3000)}{number("Rotación", "rotation", -360, 360)}{number("Opacidad", "opacity", 0, 1, .05)}</div></div>;
}

function Color({ label, value, change }: { label: string; value: string; change: (value: string) => void }): JSX.Element { return <label>{label}<span className="migrated-color-control"><input type="color" value={value.startsWith("#") ? value : "#000000"} onChange={event => change(event.target.value)} /><input value={value} onChange={event => change(event.target.value)} /></span></label>; }
